CREATE DATABASE IF NOT EXISTS skills_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE skills_db;

CREATE TABLE IF NOT EXISTS skills (
    `key` VARCHAR(191) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    description TEXT NOT NULL,
    logo TEXT NOT NULL,
    tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
